services:
  - type: web
    name: rummagebazaar-frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /assets/*
        name: Content-Type
        value: text/css
        continue: true
      - path: /assets/*
        name: Content-Type
        value: application/javascript
        continue: true